import { expect, test } from '@playwright/test'

test('photo café loads every model, highlights chess pieces, and opens playable aisle', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('response', response => {
    if (response.url().includes('.glb') && !response.ok()) errors.push(`Model failed: ${response.url()}`)
  })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.getByText('Photo demo · estimated dimensions')).toBeVisible()
  await page.getByRole('button', { name: /AI Reconstruct/ }).click()
  await expect(page.getByText('Semantic twin')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeEnabled()
  const graph = await page.evaluate(() => window.__intelidarScene!.graph!)
  expect(graph.room.id).toBe('photo-cafe-8179')
  expect(graph.objects).toHaveLength(53)
  expect(new Set(graph.objects.flatMap(o => o.assetId ?? [])).size).toBe(24)
  await page.screenshot({ path: testInfo.outputPath('cafe-overview.png') })
  await page.getByRole('textbox', { name: /ask the spatial assistant/i }).fill('Show me the chess pieces')
  await page.getByRole('textbox', { name: /ask the spatial assistant/i }).press('Enter')
  await expect(page.locator('.reply')).toContainText('5 matching objects')
  await expect(page.getByRole('button', { name: /Ivory chess king/ })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: /Ivory chess king/ }).click()
  await page.getByRole('button', { name: /Ivory chess king/ }).click()
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect.poll(() => page.evaluate(() => window.__intelidarPlay?.grounded)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('cafe-interior.png') })
  expect(errors).toEqual([])
  await page.getByRole('button', { name: 'Exit play' }).click()
  await page.getByRole('button', { name: 'Renovate', exact: true }).click()
  await page.getByLabel('Search furniture').fill('chess')
  await page.getByRole('button', { name: /Chess king.*m/ }).click()
  await page.getByRole('button', { name: 'Add Chess king', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Furniture added')
})
